scrape: # Do not change these
  url: "https://documents.gov.lk/view/extra-gazettes/egz.html"

output: # Do not change these
  metadata_dir: "metadata"
  years_json: "metadata/years.json"
  doc_metadata_json: "metadata/doc_metadata.json"
  download_metadata_json: "metadata/download_metadata.json"
  log_record_dir: "records"
  log_success: "successfully_archived.csv"
  log_failure: "failed_to_archive.csv"
  log_unavailable: "document_unavailable.csv"
  log_classification: "document_classification.csv"

archive: # Change on your preference
  archive_location: "path-to-your-local-archive-location" # Local archive location
  archive_base_url: "your-archive-repo-base-url"
  force_download_base_url: "your-rawgithubusercontent-base-url"

credentials: # Change on your preference
  divert_deepseek_api_key: your-deepseek-divert-api-key-from-bijira # Set your key
  divert_url_deep_seek: your-deepseek-divert-url-from-bijira # Set your URL
  
